FROM node:18 AS ninjadev-nin
SHELL ["/bin/bash", "-c"]
RUN npm config set fund false audit false update-notifier false loglevel notice \
&&  npm_config_loglevel=silent npm install -g ninjadev-nin@v24.0.0


FROM ninjadev-nin
EXPOSE 8080
WORKDIR /app
COPY --chmod=755 entrypoint.sh /
USER 1000:1000
RUN npm config set fund false audit false update-notifier false loglevel notice
ENTRYPOINT ["/entrypoint.sh"]
